#:schema node_modules/wrangler/config-schema.json

name = "bimaakbar"
main = "src/index.ts"
compatibility_date = "2026-10-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bimaakbar-db"
database_id = "e0d4eadf-3ec3-4a15-bdbc-ec6abe415191"

[observability]
enabled = true

[triggers]
crons = ["0 */6 * * *"]

[vars]
TELEGRAM_CHAT_ID = "1605070949"

REPOS = "bimaakbar-dev/yukionime,bimaakbar-dev/yukio-data,bimaakbar-dev/yukio-api,orchixs/yukio-api,bimaakbar-dev/yukio-bot,bimaakbar-dev/qimochi"
WORKERS = "w1:https://yukio-api.bimaakbar.workers.dev,w2:http://yukio-api.codeskycloud.workers.dev"

[dev]
port = 8787
local_protocol = "http"